name: Staging Deployment

on:
  pull_request:
    branches: [staging]
    types: [opened, reopened, synchronize]
  push: 
    branches:
      - staging

      

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
 # Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Staging Branch of Website
        uses: actions/checkout@v3
        with:
          ref: staging
      - name: modify files
      # removes .git folder to avoid conflicts with other repo 
      # inserts value for key baseurl: "/website-staging" 
        run: |
          rm -rf .git
          sed -i 's/\(^baseurl:\).*/\1 "\/website-staging" /' _config.yml
      - name: Push to website-staging repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.STAGING_KEY }}
        with:
          source-directory: .
          destination-github-username: 'usds'
          destination-repository-name: 'website-staging'
          target-branch: main
